export default {
  Chennai: [
    "Alandur",
    "Ambattur",
    "Aminjikarai",
    "Ayanavaram",
    "Egmore",
    "Guindy",
    "Kolathur",
    "Maduravoyal",
    "Mambalam",
    "Mathavaram",
    "Mylapore",
    "Perambur",
    "Purasawalkam",
    "Sholinganallur",
    "Tiruvottiyur",
    "Tondiarpet",
    "Velachery",
  ],
  Coimbatore: [
    "Coimbatore North",
    "Coimbatore South",
    "Trippur",
    "Mangalam",
    "Somanur",
    "Karumathampatti",
    "Pollachi",
    "Sulur",
    "Mettupalayam",
    "Thondamuthur",
    "Perur",
    "Annur",
  ],
  Madurai: [
    "Melur",
    "Thiruparankundram",
    "Madurai North",
    "Madurai South",
    "Madurai West",
    "Madurai East",
  ],
  Erode: [
    "Erode East",
    "Erode West",
    "Perundurai",
    "Gobichettipalayam",
    "Bhavani",
    "Sathyamangalam",
    "Modakkurichi",
  ],
  Salem: [
    "Salem South",
    "Salem North",
    "Salem West",
    "Omalur",
    "Attur",
    "Edappadi",
  ],
  Tiruchirappalli: [
    "Srirangam",
    "Thuraiyur",
    "Lalgudi",
    "Musiri",
    "Manapparai",
    "Lalgudi",
  ],
  Thanjavur: [
    "Thanjavur East",
    "Thanjavur West",
    "Pattukottai",
    "Kumbakonam",
    "Papanasam",
  ],
  Kancheepuram: [
    "Sriperumbudur",
    "Chengalpattu",
    "Tambaram",
    "Uthiramerur",
    "Pallavaram",
  ],
  Vellore: [
    "Vellore City",
    "Walajah",
    "Katpadi",
    "Gudiyatham",
    "Tirupattur",
  ],
  Tirunelveli: [
    "Tirunelveli North",
    "Tirunelveli South",
    "Palayamkottai",
    "Ambasamudram",
    "Sankarankovil",
  ],
  Thoothukkudi: [
    "Thoothukkudi North",
    "Thoothukkudi South",
    "Kovilpatti",
    "Tiruchendur",
    "Ambasamudram",
  ],
  Nilgiris: [
    "Udhagamandalam",
    "Coonoor",
    "Kotagiri",
    "Gudalur",
  ],
  Ramanathapuram: [
    "Ramanathapuram",
    "Rameswaram",
    "Paramakudi",
    "Kadaladi",
  ],
  Dindigul: [
    "Dindigul East",
    "Dindigul West",
    "Palani",
    "Oddanchatram",
  ],
  Tiruppur: [
    "Tiruppur North",
    "Tiruppur South",
    "Avinashi",
    "Uthukuli",
  ],
  Karur: [
    "Karur",
    "Kulithalai",
    "K.Paramathi",
    "Krishnarayapuram",
  ],
  Madurai: [
    "Madurai North",
    "Madurai South",
    "Thiruparankundram",
    "Melur",
  ],
  // Add more districts similarly...
};
